spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/shop
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 123123


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  config: classpath:log4j2.xml


server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800


imagePath: D:\MyProject\personal_project\ShoppingMall\shop\src\main\resources\static\img