/*INSERT INTO AUTHORITY (ID, AUTHORITY) VALUE (1, 'ADMIN');
INSERT INTO AUTHORITY (ID, AUTHORITY) VALUE (2, 'USER');

INSERT into CATEGORY (NAME) value ('PS4');
INSERT into CATEGORY (NAME) value ('PS5');
INSERT into CATEGORY (NAME) value ('SWITCH');
INSERT into CATEGORY (NAME) value ('XBOX');
*/